const interests: string[] = [
    "Web Development",
    "Graphic Design",
    "Digital Marketing",
    "Photography",
    "Video Editing",
    "Data Science",
    "Writing & Blogging",
    "Music Production",
    "Cooking & Baking",
    "Fitness & Nutrition",
    "Public Speaking",
    "Language Learning",
    "Entrepreneurship",
    "Game Development",
    "UI/UX Design",
    "Mobile App Development",
    "Cybersecurity",
    "Animation",
    "E-commerce",
    "Financial Literacy",
    "Gardening & Horticulture",
    "Painting & Drawing",
    "Mindfulness & Meditation",
    "Yoga & Pilates",
    "Martial Arts",
    "Creative Writing",
    "Storytelling",
    "Pottery & Ceramics",
    "Home Brewing",
    "Travel & Culture",
    "Astrology",
    "Astronomy",
    "Geography",
    "History",
    "Classical Music",
    "Music Theory",
    "Economics",
    "Psychology",
    "Philosophy",
    "Sociology",
    "Political Science",
    "Environmental Science",
    "Sustainable Living",
    "Fashion Design",
    "Interior Design",
    "Woodworking",
    "Carpentry",
    "Automotive Repair",
    "Home Improvement",
    "Personal Finance",
    "Investing & Stock Market",
    "Chess & Strategy Games",
    "Public Relations",
    "Event Planning",
    "Wildlife Conservation",
    "Botany",
    "Marine Biology",
    "Zoology",
    "Film & Cinematography",
    "Podcasting",
    "Journalism",
    "Genealogy & Ancestry",
    "Mythology & Folklore",
    "Poetry",
    "Theater & Acting",
    "Speechwriting",
    "Stand-up Comedy",
    "Fishing",
    "Birdwatching",
    "Hiking & Outdoor Survival",
    "Archery",
    "Cycling",
    "Rock Climbing",
    "Skiing & Snowboarding",
    "Scuba Diving",
    "Sailing",
    "Origami & Paper Crafts",
    "Jewelry Making",
    "Knitting & Crochet",
    "Leatherworking",
    "Calligraphy",
    "DIY Crafts",
    "Parenting & Childcare",
    "Pet Care & Training",
    "Nutrition Science",
    "Herbalism",
    "Acupuncture",
    "First Aid & CPR",
    "Disaster Preparedness",
    "Astronomy & Stargazing"
];


export default interests